ERROR - 2022-05-16 17:35:49,243 - process: 20132 - utils.py - polls.utils - 76 - utils - [WinError 3] 系统找不到指定的路径。: 'E:\\5703\\git_repository\\projects\\undefined'
Traceback (most recent call last):
  File "E:\5703\git_repository\polls\utils.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "E:\python\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\python\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\python\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\python\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\python\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\python\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\python\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\5703\git_repository\polls\views.py", line 414, in project_tree
    tree = get_tree(join(path, project_name))
  File "E:\5703\git_repository\polls\utils.py", line 101, in get_tree
    for file in os.listdir(path):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\5703\\git_repository\\projects\\undefined'
